apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespaces.backend }}
stringData:
  REDIS_PASSWORD: {{ .Values.database.redis.password }}
  POSTGRES_USER: {{ .Values.database.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.database.postgres.password }}
  REDIS_HOST: {{ include "devops-app.redisDns" . }}
