apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespaces.db }}
stringData:
  REDIS_PASSWORD: {{ .Values.database.redis.password }}
  POSTGRES_USER: {{ .Values.database.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.database.postgres.password }}
