{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Values.namespaces.frontend }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.ingressClassName }}
  {{- if .Values.frontend.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.frontend.ingress.host }}
    secretName: {{ .Values.frontend.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}
