---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.frontend }}
  labels:
    name: {{ .Values.namespaces.frontend }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.backend }}
  labels:
    name: {{ .Values.namespaces.backend }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.db }}
  labels:
    name: {{ .Values.namespaces.db }}
