{{- if .Values.frontend.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend.tls.secretName }}
  namespace: {{ .Values.namespaces.frontend }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  # Base64-encoded TLS certificate and key
  tls.crt: {{ .Values.frontend.tls.crt | quote }}
  tls.key: {{ .Values.frontend.tls.key | quote }}
{{- end }}
