apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: backend-ns
data:
  REDIS_HOST: redis-0.redis.db-ns.svc.cluster.local
  REDIS_PORT: "6379"
  POSTGRES_HOST: postgres-0.postgres.db-ns.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: appdb
