apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: backend-ns
stringData:
  REDIS_PASSWORD: redispass
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppass
  REDIS_HOST: redis-0.redis.db-ns.svc.cluster.local # Added as precaution
